### ISSUE TITLE
New deployment strategy

### ISSUE THREAD

**Issue by libremente** [open-education-polito/fare-platform#130]
## Expected Behavior
A docker deployment strategy must be implemented for both prod and stage

## TODO
- [ ] Design the deployment strategy
- [ ] Setup the volumes
- [ ] Setup the ENVS  in the Dockerfiles
- [ ] Create a dedicated FARE docker-compose file
- [ ] Build the image via CI tagged with the latest version
- [ ] Create a DockerHub project dedicated to the project
- [ ] Push the image on DockerHub
- [ ] Create a dedicate ENVS file to use in staging and prod deployments
- [ ] Create certs and push them in docker image
- [ ] Test on staging platform
- [ ] Test backups and rollbacks
- [ ] Document the strategy
- [ ] Update ADR
